site_name: imza.io Platform
site_description: imza.io platformu için mimari ve ürün dokümantasyonu
site_url: http://127.0.0.1:8000/platform
repo_name: imza-io/platform
repo_url: https://github.com/imza-io/platform

theme:
  name: material
  language: tr
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.expand
    - toc.integrate
    - content.code.copy
    - content.tabs.link
  logo: _assets/images/logo.svg
  favicon: _assets/images/logo.svg
  palette:
    - scheme: default
      primary: custom
      accent: custom
      toggle:
        icon: material/weather-night
        name: Koyu moda geç
    - scheme: slate
      primary: custom
      accent: custom
      toggle:
        icon: material/weather-sunny
        name: Aydınlık moda geç
  font:
    text: Montserrat
    code: JetBrains Mono

nav:
  - Anasayfa: index.md
  - Mimari:
    - Genel Bakış: architecture/overview.md
    - C4 Modeli:
      - Context: architecture/c4/context.md
      - Container: architecture/c4/container.md
      - Component: architecture/c4/component.md
      - Code: architecture/c4/code.md
  - Süreçler: processes/index.md
  - Ürünler:
    - Genel Bakış: products/index.md
    - SignGate:
      - Ürün: products/signgate/index.md
      - Mimari: products/signgate/architecture.md
      - API Referansı: products/signgate/api.md
      - Entegrasyon: products/signgate/integration.md
      - Dağıtım: products/signgate/deployment.md
      - Ticari Bilgiler: products/signgate/commercial.md
  - Projeler:
    - Genel: projects/index.md
    - Örnek Proje:
      - Proje: projects/sample-project/index.md
      - v0.1.0: projects/sample-project/releases/0.1.0.md
    - SignGate:
      - Proje: projects/signgate/index.md
      - Validator: projects/signgate/validator.md
      - v2.0.1 (Taslak): projects/signgate/releases/2.0.1.md
      - v2.0.0: projects/signgate/releases/2.0.0.md
  - DevOps:
    - Redis TLS: deployment/redis-tls.md
    - Elastic APM: deployment/elastic-apm.md
    - Saklama & Sampling: deployment/elastic-retention.md
    - Scriptler: deployment/scripts.md

markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.superfences
  - pymdownx.emoji
  - pymdownx.details
  - pymdownx.keys
  - plantuml_markdown:
      server: https://www.plantuml.com/plantuml
      format: svg
      base_dir: docs
      http_method: POST

plugins:
  - search

extra_javascript:
  - https://unpkg.com/mermaid@10.9.0/dist/mermaid.min.js
  - _assets/javascripts/mermaid-init.js

extra_css:
  - _assets/styles/overrides.css

extra:
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/imza-io
    - icon: fontawesome/solid/globe
      link: https://imza.io
