version: "3.8"
services:
  redis:
    image: redis:7-alpine
    container_name: "${COMPOSE_PROJECT_NAME}_redis"
    restart: unless-stopped
    ports:
      - "${REDIS_TLS_PORT:-6379}:6379"
    command:
      - sh
      - -c
      - >-
        redis-server --appendonly yes
        --requirepass ${REDIS_PASSWORD}
        --tls-port 6379 --port 0
        --tls-cert-file /tls/redis.crt
        --tls-key-file /tls/redis.key
        --tls-ca-cert-file /tls/ca.crt
    volumes:
      - ./data:/data
      - ./tls:/tls:ro
