name: Deploy Docs

on:
  push:
    branches: ["main", "master"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install MkDocs deps
        run: |
          python -m pip install --upgrade pip
          pip install -r docs/requirements.txt

      - name: Start PlantUML server
        run: |
          docker run -d --name plantuml \
            -p 8080:8080 \
            -e PLANTUML_LIMIT_SIZE=8192 \
            -e JAVA_OPTS="-Dplantuml.include.path=/workspace/docs -DPLANTUML_SECURITY_PROFILE=UNSECURE" \
            -v "${{ github.workspace }}/docs:/workspace/docs:ro" \
            plantuml/plantuml-server:jetty
          # simple health check
          for i in {1..20}; do curl -fsS http://localhost:8080/ || sleep 1; done

      - name: Build site (local PlantUML)
        run: mkdocs build --clean -f mkdocs.local.yml

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './site'

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
